### PR TITLE
Updated starter from Webpack 4 to Webpack 5

### PR DESCRIPTION
**Pull request by fergiemcdowall**
Hopefully this update to the `webpack-starter` repo will be useful for others. Please let me know if any further adjustments are necessary! :)

Its a bit tricky to make `webpack@5` play nicely with `level`- several non-obvious incantations are needed. The config is as concise as possible, but is still more verbose than the config for `webpack@4`. For this reason I have moved all of the webpack build options out of `package.json` and into `webpack.config.js`

### CODE REVIEW

**Comment by vweevers** [comment]
I liked it better before the last commit (8650631), this starter should be as simple as possible.

**Comment by fergiemcdowall** [comment]
@vweevers Agreed- I didnt actually mean for that last commit to be included in this pull request- it was just a private experiment for myself, and not meant for public consumption (TIL that a PR will continue to append commits made to the branch after the PR is submitted).

**Comment by fergiemcdowall** [comment]
This is the intended PR -> https://github.com/fergiemcdowall/webpack-starter/releases/tag/v0.1.x

**Comment by fergiemcdowall** [comment]
@vweevers what do you think now?

**Comment by vweevers** [comment]
Do we need to bump this?

https://github.com/Level/webpack-starter/blob/f6ae69929854486238a13bada3e80c29a11cdaf1/package.json#L24-L26

**Comment by fergiemcdowall** [comment]
@vweevers sorry for the late reply- didnt see the notification until now.

I see that the latest version of webpack [specifies](https://github.com/webpack/webpack/blob/master/package.json) `"node": ">=10.13.0"`, so I guess that would be new baseline for this demo?

**Comment by vweevers** [comment]
OK, let's update our `engines.node` to match webpack.

**Comment by fergiemcdowall** [comment]
done.

**Review by vweevers — APPROVED** [review]

**Comment by vweevers** [comment]
Thanks!

**Comment by fergiemcdowall** [comment]
My pleasure- thanks for publishing this module in the the first place 🙂👍

**Pull request merged**
